### ISSUE TITLE
compile error in ClassTable.v

### ISSUE THREAD

**Issue by h908714124** [hephaestus-pl/coqfj#1]
make fails with this error

```
File "./src/FJ/ClassTable.v", line 37, characters 38-48:
Error: In environment
C : ClassName
The term "ClassTable" has type "[ClassDecl] -> Prop"
which should be Set, Prop or Type.

```

coqtop version is 8.6

**Comment by pedrotst** [comment]
Even though it was not a matter of coqtop version, please let me know if you have other problems with version 8.6 because I've been using v8.5 all along.

Probably I'll need to bump some files for the new version.
